// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Hotel_Corporate_System.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AllNew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllNew));
        
        string IMigrationMetadata.Id
        {
            get { return "201801011258439_All-New"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
