//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Corporate_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientService
    {
        public System.Guid Id { get; set; }
        public bool IsBooking { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public System.Guid ClientId { get; set; }
        public System.Guid ServiceId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
