//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Corporate_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalOrder
    {
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public System.Guid OrderTypeId { get; set; }
        public System.Guid RequestedById { get; set; }
        public System.Guid AssignedToId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual OrderType OrderType { get; set; }
    }
}
