//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Corporate_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.ClientAccommodations = new HashSet<ClientAccommodation>();
        }
    
        public System.Guid Id { get; set; }
        public int Class { get; set; }
        public int Beds { get; set; }
        public string Number { get; set; }
        public decimal Cost { get; set; }
        public System.Guid FloorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAccommodation> ClientAccommodations { get; set; }
        public virtual Floor Floor { get; set; }
    }
}
